// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: attachments.sql

package repo

import (
	"context"
)

const getAttachmentsByMessage = `-- name: GetAttachmentsByMessage :many
SELECT id, message_id, file_url, file_type, created_at
FROM attachments
WHERE message_id = $1
`

func (q *Queries) GetAttachmentsByMessage(ctx context.Context, messageID string) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileUrl,
			&i.FileType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO attachments (message_id, file_url, file_type)
VALUES ($1, $2, $3)
RETURNING id, message_id, file_url, file_type, created_at
`

type InsertAttachmentParams struct {
	MessageID string `json:"message_id"`
	FileUrl   string `json:"file_url"`
	FileType  string `json:"file_type"`
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment, arg.MessageID, arg.FileUrl, arg.FileType)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileUrl,
		&i.FileType,
		&i.CreatedAt,
	)
	return i, err
}
